from numpy import ndarray

def a(n: float, r: ndarray) -> ndarray: ...

def profile1(r: ndarray) -> tuple[ndarray, ndarray]: ...

def profile2(r: ndarray) -> tuple[ndarray, ndarray]: ...

def profile3(r: ndarray) -> tuple[ndarray, ndarray]: ...

def profile4(r: ndarray) -> tuple[ndarray, ndarray]: ...

def profile5(r: ndarray) -> tuple[ndarray, ndarray]: ...

def profile6(r: ndarray) -> tuple[ndarray, ndarray]: ...

def profile7(r: ndarray) -> tuple[ndarray, ndarray]: ...
